### ISSUE TITLE
typo: ~plateform~ platform

### ISSUE THREAD

**Issue by evandrix** [Phantas0s/devdash#1]
additionally, compile error

- [internal/platform/github.go](): `"github.com/google/go-github/v27/github"` => it's now v28 actually, but it's probably alright to omit the `vXX`

- [internal/platform/github.go](): patch below

```
opt := &github.BranchListOptions{
	ListOptions: github.ListOptions{PerPage: limit},
}
bs, _, err := g.client.Repositories.ListBranches(context.Background(), g.owner, repo, opt)
```

**Comment by Phantas0s** [comment]
Thanks a lot for that!

`github.com/google/go-github/` without the `vXX` should only be used without go module.

I don't have any compilation error with "github.com/google/go-github/v28"

**Comment by Phantas0s** [comment]
I reproduced the compilation error. Weirdly enough, when using go get, the versioning is totally ignored and `go-github` is fetched from master. When using go module outside of GOPATH, I can't fetch another version than `v17` or `v28`, even when I use `@master`.
