### ISSUE TITLE
Track pull requests of interest

### ISSUE THREAD

**Issue by Bekreth** [Phantas0s/devdash#11]
This may be out of the purview of what you're intending to tackle with this project, but for a while now I've been hunting for a dashboard that can track pull requests that I'm involved in.  The functionality I'd most hope for is that I could add a PR to the dashboard, and whenever there's a delta (added comments, resolved issues, etc...) it would become highlighted on the dashboard until I've "recognized" the update. I frequently deal with BitBucket and Github repositories, so it'd be really nice to have an aggregate view from these different source.

**Comment by Phantas0s** [comment]
That's an interesting idea. I'm on another CLI right now, but I think I'll come back to devdash in the next weeks. I'll think about that meanwhile, it shouldn't be too hard to implement (depending on the BitBucket API of course :D)

**Comment by Phantas0s** [comment]
Too busy to implement that at the moment; PR are welcome :)
