### ISSUE TITLE
Is it possible on box widgets to show multiple lines on command output? 

### ISSUE THREAD

**Issue by tiagoprn** [Phantas0s/devdash#12]
Hello @Phantas0s ! Thank you for devdash, it is an awesome tool I am incorporating to my daily routine. 

I have a question regarding showing in a box the output of a command that expands to multiple lines.The box only outputs the first line, and I cannot find other way in the documentation to solve that. I thought the height option would be enough, but it is not. 

I am attaching here an image with an example showing my devdash yaml configuration, the multilines output I am waiting (directly from the scripts) and what I am getting from running on devdash using my configuration. 

Is that possible? If not, I would guess that as a new implementation you could do something similar to the table widget and name it to lh.multilines_box, e.g.

That is the only feature I miss from devdash now, and I think it limits its' potential to not be there.

[Here is the image](https://s3.us-west-1.wasabisys.com/tiagoprnl-public/2021-04-22_05-57.png).

Count on me if you need more information and someone to help you with testing that.

Thank you!

**Comment by Phantas0s** [comment]
Hello @tiagoprn :)

Thanks for the kind words! 

It works normally, and I could make your script work too with a height of 25. I've changed quite a lot of things for the last version of DevDash (released today, v0.5.0) so you could try again.

**Comment by tiagoprn** [comment]
Hey @Phantas0s ! Thank you very much, I will try again and ping you back with the results. Have a great week!

**Comment by tiagoprn** [comment]
Working awesomely @Phantas0s , thank you tons! :rocket:

**Comment by Phantas0s** [comment]
@tiagoprn Glad it works :) thanks for your interest in my work!
