### ISSUE TITLE
go get install fails with cannot use &opt (type *github.ListOptions) as type *github.BranchListOptions

### ISSUE THREAD

**Issue by samof76** [Phantas0s/devdash#2]
First of all thanks for this excellent project.

Some details about my environment

OS: Ubuntu 18.04
Go version: 1.13(managed using asdf)

Tried to do the following,

```
go get -u github.com/Phantas0s/devdash/cmd/devdash
```
And ended up with this

```
# github.com/Phantas0s/devdash/internal/platform
/home/sam/.asdf/installs/golang/1.13/packages/src/github.com/Phantas0s/devdash/internal/platform/github.go:547:88: cannot use &opt (type *github.ListOptions) as type *github.BranchListOptions in argument to g.client.Repositories.ListBranches
```

**Comment by Phantas0s** [comment]
Thanks for the kind words and sorry for the delay.

I think I fixed the problem. Can you try again for me to close the issue?/
