### ISSUE TITLE
Issue on running windows (both x86 x64) precompiled binary

### ISSUE THREAD

**Issue by mmalcek** [Phantas0s/devdash#7]
Hi when I try run on windows I endup with this error message:

panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/spf13/viper.absPathify(0xd3f94e, 0x19, 0x0, 0x0)
        /home/hypnos/workspace/go/pkg/mod/github.com/spf13/viper@v1.5.0/util.go:100 +0x44f
github.com/spf13/viper.(*Viper).AddConfigPath(0xc000294300, 0xd3f94e, 0x19)
        /home/hypnos/workspace/go/pkg/mod/github.com/spf13/viper@v1.5.0/viper.go:415 +0x69
github.com/spf13/viper.AddConfigPath(...)
        /home/hypnos/workspace/go/pkg/mod/github.com/spf13/viper@v1.5.0/viper.go:412
github.com/Phantas0s/devdash/cmd.mapConfig(0xc00001cd40, 0x35, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hypnos/workspace/devdash/cmd/config.go:181 +0x12d
github.com/Phantas0s/devdash/cmd.begin(0x0, 0x0, 0x0)
        /home/hypnos/workspace/devdash/cmd/devdash.go:22 +0x137
github.com/Phantas0s/devdash/cmd.run(...)
        /home/hypnos/workspace/devdash/cmd/root.go:40
github.com/Phantas0s/devdash/cmd.glob..func1(0x1389820, 0x13c1e78, 0x0, 0x0)
        /home/hypnos/workspace/devdash/cmd/root.go:21 +0x4b
github.com/spf13/cobra.(*Command).execute(0x1389820, 0xc00003c1f0, 0x0, 0x0, 0x1389820, 0xc00003c1f0)
        /home/hypnos/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0x1389820, 0x445061, 0x13411a0, 0xc000037f78)
        /home/hypnos/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /home/hypnos/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/Phantas0s/devdash/cmd.Execute()
        /home/hypnos/workspace/devdash/cmd/root.go:33 +0x38
main.main()
        /home/hypnos/workspace/devdash/devdash.go:6 +0x27

**Comment by Phantas0s** [comment]
Hi,

Nice! You can post a pull request if you want :)

**Comment by Phantas0s** [comment]
Fixed in the last release.
